### ISSUE TITLE
类找不到

### ISSUE THREAD

**Issue by wangkaisdu** [leonindy/camel#1]
import com.dianping.phoenix.lb.model.entity.Pool
你好，最近尝试运行，发现找不到这个类，麻烦看下

**Comment by leonindy** [comment]
你好，请运行mvn compile，maven wizard插件会自动生成模型类

**Comment by leonindy** [comment]
另外如果是使用intellij idea，请把 target/generated-sources/dal-model目录标记为sources root类型文件夹
